---
version: "3"
services:
  mainnetwork:
    image: alpine:3.14
    command: ["tail", "-f", "/dev/null"]
    ports:
      - 8000:8000
      - 3000:3000
  db:
    command: "postgres -c 'shared_buffers=128MB' -c 'fsync=off' -c 'synchronous_commit=off' -c 'full_page_writes=off' -c 'max_connections=100' -c 'bgwriter_lru_maxpages=0' -c 'client_min_messages=warning'"
    restart: always
  frontend:
    network_mode: service:mainnetwork
    image: eu.gcr.io/akvo-lumen/wai-ethiopia/frontend:latest
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - backend
  backend:
    network_mode: service:mainnetwork
    image: eu.gcr.io/akvo-lumen/wai-ethiopia/backend:latest
    command: ["gunicorn", "wai.wsgi:application", "--bind", "0.0.0.0:8000"]
    depends_on:
      - db
  ci:
    network_mode: service:mainnetwork
    image: alpine:3.14
    volumes:
      - ./ci/test:/test:ro
    working_dir: /test
    entrypoint: ./entrypoint.sh
    depends_on:
      - frontend
