---
version: "3"
services:
  db:
    command: "postgres -c 'shared_buffers=128MB' -c 'fsync=off' -c 'synchronous_commit=off' -c 'full_page_writes=off' -c 'max_connections=100' -c 'bgwriter_lru_maxpages=0' -c 'client_min_messages=warning'"
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
      - ./db/script:/script:ro
    restart: always
    ports:
      - 5432:5432
  backend:
    image: eu.gcr.io/akvo-lumen/wai-sdg-portal/backend:latest
    working_dir: /app
    command: "pytest -rP"
    volumes:
      - ./backend:/app:delegated
    environment:
      - DATABASE_URL=postgresql://wai:password@db:5432/wai_test
      - SKIP_MIGRATION=yes
      - MAILJET_SECRET=notset
      - MAILJET_APIKEY=notset
      - WEBDOMAIN=notset
      - INSTANCE_NAME=notset
      - AUTH0_DOMAIN
      - AUTH0_CLIENT_ID
      - AUTH0_SECRET
      - AUTH0_AUDIENCE
    depends_on:
      - db
volumes:
  pg-data:
