---
version: "3.9"
services:
  mainnetwork:
    ports:
      - 3000:3000
      - 8000:8000
      - 5050:5050
  pgadmin:
    image: dpage/pgadmin4:5.7
    environment:
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_DEFAULT_EMAIL=dev@akvo.org
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
      - pg-admin-data:/var/lib/pgadmin
    depends_on:
      - db
    network_mode: service:mainnetwork
  backend:
    volumes:
      - ./backend:/app:delegated
      - ../akvo-config/k8s-secrets/test/wai-ethiopia:/credentials/:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/wai-service-account.json
      - AUTH0_DOMAIN=$WAI_AUTH0_DOMAIN
      - AUTH0_CLIENT_ID=$WAI_AUTH0_CLIENT_ID
      - AUTH0_AUDIENCE=$WAI_AUTH0_AUDIENCE
      - AUTH0_SECRET=$WAI_AUTH0_SECRET
      - MAILJET_SECRET=$MAILJET_SECRET
      - MAILJET_APIKEY=$MAILJET_APIKEY
      - WEBDOMAIN=$WAI_WEBDOMAIN
  worker:
    volumes:
      - ./backend:/app:delegated
      - ../akvo-config/k8s-secrets/test/wai-ethiopia:/credentials/:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/wai-service-account.json
      - MAILJET_SECRET=$MAILJET_SECRET
      - MAILJET_APIKEY=$MAILJET_APIKEY
      - WEBDOMAIN=$WAI_WEBDOMAIN
volumes:
  pg-admin-data:
