---
version: "3.9"

services:
  mainnetwork:
    image: alpine:3.14.0
    command: ["tail", "-f", "/dev/null"]
  db:
    ports:
      - 5432:5432
    image: postgres:12-alpine
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
      - ./db/script:/script:ro
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
  backend:
    image: python:3.9.7-slim-buster
    command: ["./run.sh"]
    depends_on:
      - db
    working_dir: /app
    volumes:
      - ./backend:/app:delegated
    environment:
      - POSTGRES_DB=ethiopia
      - POSTGRES_USER=wai
      - POSTGRES_PASSWORD=password
    network_mode: service:mainnetwork
volumes:
  pg-data:
